name: CI
on:
  push:
    branches:
    - main
jobs:
  split-upm:
    name: split upm branches
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: split upm branches
      run: |
        function split_and_push() {
            local package_name=$1

            local main_package="Packages/com.pixelshub.$package_name"
            local branch_name=$package_name

            # Check if required file exists
            if [ ! -e $main_package ]; then
              echo "Error: Required file for package $package_name does not exist. Aborting subtree update."
              return 1
            fi
            
            # Check if target branch does not exist or check for changes
            if [ ! -e $branch_name ] || [ ! git diff --quiet origin/main:$main_package origin/$branch_name ] ; then
              git subtree split -P $main_package -b $branch_name
              git push -u origin $branch_name
            else
              echo "No changes for package $package_name. Skipping subtree update."
            fi
          }
          
          split_and_push packageexample
